### ISSUE TITLE
General Plan: What I still have todo

### ISSUE THREAD

**Issue by DanielBoigk** [DanielBoigk/CalderonEITFEM#1]
- [ ] Why is the extracted Gradient totally different from the given Neumann Boundary?
- [ ] Implement functions that mediate between Circle and array files
    - [ ]  Extract Mesh data to array and plot.
    - [ ] Readout boundary.
- [ ] Plot Solution from circular Mesh
- [x] Construct Square Mesh explicitely from .geo or .msh file.
- [ ] Write function that assigns labels to mesh explicitely.
    - [ ] boundary elements
    - [ ] implement function that  
- [x] Find way to print solver output in Gridap
- [x] Find way to adjust parameters of solver in Gridap
- [ ] Implement reference solution in Ferrite
    - [ ] Find way to run Ferrite in same Enviroment
    - [ ] Do Pull request for Solution in GridapGmsh if solution to problem is found.
- [x] Ask @fverdugo , @JordiManyer etc. on how to extract Gradient with something that is remotely performant.  
![image](https://github.com/DanielBoigk/CalderonEITFEM/assets/71269893/c9522246-d9c8-4001-b2e1-417ea01e75bb)
- [ ] Multiple Function doing roughly the same thing... Merge into one.

- [ ] Make proper Julia Package
    - [ ] Add toml file
    - [ ] Include the Python snippets properly 
- [ ] Dokument what every function does.
    - [ ] Improve Readme.md 

If necessary within the next weeks:
- [ ] make it available for training in Pytorch
- [ ] Calculate Matrix approximation of Boundary operators. Give explizit representation:
    - [ ] using single boundary points
    - [ ] using fourier series
    - [ ] of Dirichlet-to-Neumann operator
    - [ ] of Neumann-to-Dirichlet operator 
 
## Longterm Goals:
- [ ] Clean up code/functions/API
- [ ] Improve code for performance.
- [ ] Implement Methods using arbitrary mesh shape
- [ ] Do the 3D FEM Solution
- [ ] Create Python interface
- [ ] Find way to upscale arrays to arbitrary precision.
    - [ ] Find way to calculate gradient
- [ ] Extend to include arbitrary periodic signals, assuming complex conductivity values (i.e. inductive/capacitive resistances.)

**Comment by DanielBoigk** [comment]
Gradient Problem is semi solved. Works quite fast for mesh generated from file evaluated at mesh points. For Gridap generated square mesh it still runs terrible. Not as terrible as the multiple hours above but still more than a minute.
